# Generated by Django 2.2.5 on 2019-11-19 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(help_text='Authorization token', max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('name', models.CharField(help_text="User's name", max_length=40, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(help_text="User's email", max_length=254)),
                ('meta', models.TextField(help_text="User's meta data", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_data_value', models.TextField(help_text="Owned data's id")),
                ('data_type', models.TextField(help_text='Data type')),
                ('timestamp', models.BigIntegerField(help_text='Data store timestamp')),
                ('id_owner', models.ForeignKey(help_text='This data belongs to', on_delete=django.db.models.deletion.CASCADE, to='authorization_app.User')),
            ],
        ),
    ]
